name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: CI
        run: zig build ci

  build:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-linux, x86_64-linux, aarch64-linux, riscv64-linux ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build
        run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}
      - name: Archive executable
        uses: actions/upload-artifact@v4
        with:
          name: zebrac-${{ matrix.target }}
          path: zig-out/bin/*
